from __future__ import annotations

from typing import Protocol, Any


class AuditLogRepository(Protocol):
    def append(self, entry: dict[str, Any]) -> dict[str, Any]: ...
    def list_logs(self, limit: int = 50, **filters: str | None) -> list[dict[str, Any]]: ...


class EvalRunRepository(Protocol):
    def save(self, run: dict[str, Any]) -> None: ...
    def list_runs(self, limit: int = 20) -> list[dict[str, Any]]: ...


class CrisisEventRepository(Protocol):
    def get(self, event_id: str) -> dict[str, Any] | None: ...
    def list_events(self, **kwargs: Any) -> list[dict[str, Any]]: ...
